# Header
menu:
  Home: /
  Archives: /archives

# Title on top left of menu. Leave empty to use main blog title
menu_title: Blog

# URL of the Home page image
index_cover: https://raw.githubusercontent.com/leido/leido.github.io/master/images/cover.png

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  duoshuo_shortname: 4disland
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# set your own favicon
favicon:

# Social Accounts
# twitter_url:
# twitter_handle:
# facebook_url:
github_url: https://github.com/leido
weibo_url: http://weibo.com/neon1
# linkedin_url:
# mailto: dileu12@outlook.com